Homeland Security Investigations
The ICE Homeland Security Investigations (HSI) directorate is a critical asset in the ICE mission, responsible for investigating a wide range of domestic and international activities arising from the ...
http://www.ice.gov/about/offices/homeland-security-investigations/index.htm
